export const courses = [
  { label: "SAT", value: "SAT" },
  { label: "AP", value: "AP" },
  { label: "IB", value: "IB" },
  { label: "GCSE A-Level", value: "GSCE-A-Level" },
  { label: "GRE", value: "GRE" },
  { label: "GMAT", value: "GMAT" },
  { label: "LSAT", value: "LSAT" },
  { label: "MCAT", value: "MCAT" },
  { label: "USMLE Step 1", value: "USMLE Step 1" },
  { label: "USMLE Step 2", value: "USMLE Step 2" },
  { label: "USMLE Step 3", value: "USMLE Step 3" },
  { label: "NCLEX Bar Exam", value: "NCLEX Bar Exam" },
  { label: "CPA Exam", value: "CPA Exam" },
  { label: "CFA Level 1", value: "CFA Level 1" },
  { label: "CFA Level 2", value: "CFA Level 2" },
  { label: "CFA Level 3", value: "CFA Level 3" },
  { label: "PMP", value: "PMP" },
  { label: "PLAB 1", value: "PLAB 1" },
  { label: "PLAB 2", value: "PLAB 2" },
  { label: "IELTS", value: "IELTS" },
  { label: "TOEFL", value: "TOEFL" },
  { label: "OET", value: "OET" },
] as const;
